tabWidth: 4
useTabs: false
semi: false
singleQuote: true
trailingComma: es5
arrowParens: avoid
bracketSpacing: true
overrides:
  - files: ['*.json', '*.yml', '*.yaml']
    options:
      tabWidth: 2
  - files: [layouts/**/*.html]
    options:
      parser: go-template
