language: ruby
rvm:
  - 2.1
  - 2.2
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y wkhtmltopdf
script:
  - bundle exec rake clean
  - bundle exec rake build
  - bundle exec rake test
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer