baseURL = "https://skyaaron.com/"
languageCode = "en-us"
title = "Aaron Sky"
enableRobotsTXT = true

[author]
name = "Aaron Sky"
caption = "Mobile Tools Developer"
email = "aaronsky@skyaaron.com"

[params.identity.links]
twitter = "https://twitter.com/metc_sky/"
github = "https://github.com/aaronsky/"
linkedin = "https://www.linkedin.com/in/aaronsky/"
npm = "https://www.npmjs.com/~aaronsky"

[[params.identity.links.mastodon]]
instance = "macaw.social"
username = "sky"
link = "https://macaw.social/@sky"

[params.experience.links]
dropbox = "https://dropbox.com/"
twitter = "https://twitter.com/"
wayfair = "https://www.wayfair.com/"
sapient = "https://www.publicissapient.com/"
xamarin = "https://dotnet.microsoft.com/apps/xamarin"

[markup.highlight]
noClasses = false

[security.exec]
osEnv = ['(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$', '^ASDF_DIR$', '^HOME$']
