[tools]
hugo-extended = "0.143"
node = "latest"

[env]
_.path = ['{{config_root}}/node_modules/.bin']
HUGO_VERSION = { value = "{{ exec(command='hugo version') }}", tools = true }

[tasks.clean]
run = "rm -rf bin public resources tmp"

[tasks.format]
run = "prettier --write ."

[tasks.dev]
run = "hugo serve -D"

[tasks.htmltest]
run = ["curl https://htmltest.wjdp.uk | bash", "bin/htmltest -c htmltest.yml"]
