[build]
command = "make build"

[build.environment]
HUGO_VERSION = "0.88.1"

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[[headers]]
  for = "/posts/index.xml"
  [headers.values]
    Content-Type = "application/rss+xml "
