name: docs
on: push

jobs:
  tests:
    name: htmltest site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.82.1'

      - name: Build Site
        run: make build

      - name: Run htmltest
        run: |
          curl https://htmltest.wjdp.uk | bash
          ./bin/htmltest -c htmltest.yml
